### ISSUE TITLE
Port of FS296 - max gradient computation is not thread safe (isosurface)

### ISSUE THREAD

**Issue by wfpokorny** [POV-Ray/povray#113]
Details:

It appears as a side effect of investigation of FS#294: the code in isosurf.cpp, inside bool IsoSurface::Function_Find_Root_R(ISO_ThreadData& itd, const ISO_Pair\* EP1, const ISO_Pair\* EP2, DBL dt, DBL t21, DBL len, DBL& maxg)

```
    if(gradient < temp)
            gradient = temp;
```

is not thread-safe (The code is used at render time, there is a data race between < and = operation, as gradient is stored in the global object and accessed in write mode by the cited code)

It is only important if the gradient is initially undervaluated (otherwise, all is fine, no write-access)

Reference: http://bugs.povray.org/task/296

**Comment by c-lipka** [comment]
This potential for a race condition is known, but accepted due to being very low-risk in terms of impact:

- The `gradient` field is a guesstimated value anyway, so some error won't hurt too much.
- The field is guesstimated so frequently that any such error early on will most likely be corrected later (at least approximately), while such an error at a late stage will most likely have little impact on the outcome.

It was therefore deliberately decided to favour speed over thread-safety in this case.
