### ISSUE TITLE
Port of FS127 - Expandable arrays

### ISSUE THREAD

**Issue by wfpokorny** [POV-Ray/povray#197]
http://bugs.povray.org/task/127

(Per Christoph's comments, certain forms of 1d arrays grow dynamically as of 3.7.1. See: http://wiki.povray.org/content/Reference:Array for details and the github comments to this issue.)

---------------
Details:

Currently, arrays are of a fixed size. You can't add or remove items to/from an array. I think it would like arrays to be expandable with no fixed and pre-determined size.

---------------
Comments:

---
Comment by Grimbert Jérôme (Le_Forgeron) - Thursday, 10 June 2010, 17:04 GMT+5

Re-allocation on assignment ?
dimension_size() & dimensions() might suggest that the basic support is already there.

Biggest issue might be that multiple dimensions arrays are so far assumed to be regular in size over indexes.
(a 2D is a rectangle, 3D a box, and so on). Most variable size multi-dimension arrays usually consider that they are just holder of N-1 D arrays...

Removing element from array ? how do you make such thing ?

To resume: why not get extension on assignemnt, but as array are not "empty" structure, it might cost a lot for multiple dimensions. (that's only a few millions cycles...)
Removal, I do not understand.

---
Comment by Christoph Lipka (clipka) - Saturday, 19 June 2010, 01:44 GMT+5

Note that items can be removed from an array by using "#undef Foo[Bar]".

---
Comment by Mike H (SharkD) - Sunday, 20 June 2010, 05:21 GMT+5

Ah, didn't realize you could undef them.

You still get a warning if you don't set the array size initially.

---
Comment by Thorsten Fröhlich (thorsten) - Sunday, 20 June 2010, 13:17 GMT+5

A little known detail about POV-Ray's arrays is that they can also contain arrays of different elements. That is, you can do things like this:

```
#declare foo = array[2];
#declare foo[0] = array[2];
#declare foo[1] = array[7];
#declare foo[0][0] = 2;
#declare foo[1][6] = sphere{1,1}
```

The idea behind this is that an array can only contain elements of the same type, but a two dimensional array is just an array of arrays. And each of these arrays can be of any type. It is quite possible to build complex structures out of this.

As such, it also is not correct that POV-Ray's arrays need to be the same size in every dimension! What follows is that one can actually build trees out of POV-Ray's arrays, among other structures.

---
Comment by Richard Callwood III (Cousin_Ricky) - Tuesday, 08 October 2013, 17:43 GMT+5

Have you seen macro Resize_Array() in arrays.inc?

---
Comment by Christoph Lipka (clipka) - Monday, 11 November 2013, 05:09 GMT+5

While Resize_Array() can get the job done, it takes an awful lot of time as the array grows

**Comment by c-lipka** [comment]
POV-Ray 3.7.1 beta adds support for 1-dimensional arrays that can grow dynamically.

**Comment by c-lipka** [comment]
> (Per Christoph's comment, 1d arrays grow dynamically as of 3.7.1. See: http://wiki.povray.org/content/Reference:Array for details.)

That's a potentially misleading simplification of my statement. POV-Ray 3.7.1 does _not_ make conventional 1D arrays (`#declare Foo = array[N];`) dynamic in size.

Instead, support for dynamic arrays is added by introducing a _new flavour_ of array, which grows automatically as needed, but is restricted to one dimension (`#declare Foo = array;`).

That said, I would like to close this issue. From what I see, the only remaining sub-issues would be:
- shrinking of dynamic arrays (which is problematic, for reasons rooted in the C++ language standard)
- multi-dimensional dynamic arrays (which could be reasonably well emulated by storing dynamic elements in dynamic elements)

If anyone considers any of these to be important enough, I think they should be raised as separate issues, so that we can close this one. Any objections?

**Comment by wfpokorny** [comment]
Thanks for the clarification the 1d growth is limited to a new flavor of array. I'll make a further edit to this issue's opening statement to clarify.  I've no objection to closing this issue.
