### ISSUE TITLE
Make check auto response 

### ISSUE THREAD

**Issue by trevorsandy** [POV-Ray/povray#240]
How can i automatically accept the image check prompt during building on Linux ? 

I see it is done in the Travis builds with no specific command or flag. 

I am trying to integrate POV-Ray into my application ([LPub3D](https://github.com/trevorsandy/lpub3d)).

**Comment by wfpokorny** [comment]
Perhaps your question will be understood by others, but I am unsure specifically what prompt you see? When I build on Ubuntu post cloning with the commands :  

cd ./unix 
 ./prebuild.sh
cd ..
./configure COMPILED_BY="wfp"
make -j4 

I get no prompts which require an answer.

**Comment by c-lipka** [comment]
When you run POV-Ray for Unix with render preview enabled (`+d`), it will keep the preview window open until you press a key or click on the preview. This is also the case when POV-Ray is run after build as part of the `make check` command.

On Travis CI, no prompt is generated because the build environment provides neither X11 nor libSDL support, so POV-Ray is built without render preview.

You have several options to work around this:

- Patch `unix/prebuild.sh` to run the test render with `-d` instead of `+d` (search the file for `check: all`).
- Invoke `make` instead of `make check` to skipping the test render entirely.
- Invoke `make` instead of `make check`, and initiate a separate test render as part of your program's build process.

**Comment by trevorsandy** [comment]
Excellent - Many thanks for your quick and comprehensive response ! Cheers,
