### ISSUE TITLE
Override povray.conf default locations 

### ISSUE THREAD

**Issue by trevorsandy** [POV-Ray/povray#244]
Is it possible to override the default conf locations by specifying the conf file on the command line for example?

I am packaging povray as a component of my application [LPub3D](https://github.com/trevorsandy/lpub3d). I would like to specify the conf params and have my instance ignore any other conf files (perhaps from an existing installation) that may exist at the default locations. Many thanks!

Cheers,

**Comment by c-lipka** [comment]
It is **not** recommended to install multiple instances of POV-Ray from the same "generation" (e.g. 3.7, encompassing both 3.7.0 and the upcoming 3.7.1) in parallel, as they **will** interfere with each other anyway, due to shared registry keys (`HKCU/Software/POV-Ray/v3.7` in this case).

If you do have to go down this route, you should instead build a modified version of POV-Ray that uses its own registry key and directory names. Having a look at the effect of the `POVRAY_IS_BETA` preprocessor macro might give you the necessary hints to accomplish this, as the beta also has its own registry key and directory names (`v3.7-beta` instead of `v3.7`).

(Note however that if you were to build a GUI version of such a derivative, you would also need to build your own editor DLLs. Beware of licensing pitfalls there.)

**Comment by trevorsandy** [comment]
Understood. Thanks. 
My question was actually targeting Linux builds but this is very useful information about limitations on windows.

You response generates 3 questions:

1 Is it necessary to have the editor module on windows - could I not (within reasonable effort) build a CLI-only version ? It seems like CLI-only approach would avoid the bulk of the registry entries. Also, perhaps a CLI-only version could use the existing .conf framework available for Unix.

2 On Linux, is it possible to bypass, and ignore, the default .conf files - i.e. pass my own .conf via the command line ? 

3 If it is not possible to go the route of question 2, can you briefly say the effort to convert the source to accept a .conf via the command line ? 
Many thanks.

P.S. If you are still looking for a cross-plat GUI front end, I suggest [Qt](https://www.qt.io/).

Cheers,

**Comment by c-lipka** [comment]
> 1 Is it necessary to have the editor module on windows - could I not (within reasonable effort) build a CLI-only version ? It seems like CLI-only approach would avoid the bulk of the registry entries. Also, perhaps a CLI-only version could use the existing .conf framework available for Unix.

(a) No, the editor module isn't strictly necessary, even for the GUI version. Though the lack of the editor module makes it a bit more cumbersome to start renders, as you have to use the "command line" input field to specify the file to render, or use the render queue feature.

(b) There does exist a (not officially supported) CLI-only variant of the Windows version, namely the "console" project. I _think_ it does use the same registry mechanisms as the GUI version though.

(c) If you're looking for a Windows CLI version that behaves pretty much like the Unix version, maybe you should really go for trying to compile the Unix version for a Windows target, using Cygwin, MinGW or a similar framework.

> 2 On Linux, is it possible to bypass, and ignore, the default .conf files - i.e. pass my own .conf via the command line ?

No, not at present.

> 3 If it is not possible to go the route of question 2, can you briefly say the effort to convert the source to accept a .conf via the command line ?

I'm not sure if it would be wise to implement such a command line option, as the povray.conf mechanism is really all about security (protecting against accidentally or maliciously bogus scenes), and allowing to override it via the command line might weaken it, so shouldn't be done without careful analysis of the security implications.

So it may be wiser to ask for the underlying goal you want to achieve in the first place, and whether that underlying goal can be achieved in a different manner.

**Comment by trevorsandy** [comment]
Excellent - Thanks again for taking the time craft a detailed answer !

I agree with your assessment of point 3.  

My goal is to have LPub3D run out of the box without any additional configuration or additional packages needed. Currently one must install or have installed the supported renderer(s). As the application is positioned for juniors and teachers who may not be deeply technical, I prefer to pursue a seamless solution.

To this end, I want to provide a POV-Ray as packaged renderer with LPub3D. Transactions will be between LPub3D editor and POV-Ray via command line only (app to app). Standard options and flags will be configurable through the LPub3D GUI. However, advanced configuration will also be possible by editing the conf files which will also be possible through the LPub3D UI.

The main features I was wanting to enable with the .conf flexibility is 1. mapping part libraries and 2 avoiding to 'corrupt' or consume configuration from an existing instance of POV-Ray.

Perhaps I can look at modifying the source to look for the conf files at the %INSTALLDIR%.

Cheers,

**Comment by c-lipka** [comment]
> The main features I was wanting to enable with the .conf flexibility is 1. mapping part libraries

I don't see how this necessitates editing `povray.conf` in any way (unless the user has customized it, in which case you can presume them to be familiar with the procedure of modifying it). Most notably, the default `povray.conf` includes the following lines (among others):

    read* = %INSTALLDIR%/include
    read* = %INSTALLDIR%/../../etc
    read* = %HOME%

Thus you can add any part library `.inc` files either...

- anywhere in or below the user's home directory (possibly via a symbolic link to a global location)
- anywhere in or below `%INSTALLDIR%/../../etc`, which would be `/usr/local/etc` or `/usr/etc` for the default POV-Ray installation locations `/usr/local/share/povray-3.7` or  `/usr/share/povray-3.7`, respectively
- if you provide a separate installation of POV-Ray, anywhere in or below that installation's `include` subdirectory

(Note that %INSTALLDIR% always applies to the installation of POV-Ray being run, not the installation of POV-Ray that originally created the `povray.conf` file.)

> 2 avoiding to 'corrupt' or consume configuration from an existing instance of POV-Ray.

To achieve that, I would simply refrain from allowing to edit `povray.conf` via the LPub3D UI in the first place, especially since anything you have to modify there may also necessitate changes to the global `povray.conf`, to which the user may not have write access. If you detect that any changes need to be made, inform the user that they need to edit the file in an external editor -- if you do things right, this should only happen if the user had already tampered with the `povray.conf` earlier, and is therefore reasonably familiar with the procedure.

> Perhaps I can look at modifying the source to look for the conf files at the %INSTALLDIR%.

Be advised that, to the best of my knowledge (IANAL), if you _distribute_ a modified version of POV-Ray you will need to make sure that it clearly identifies as a _derivative_ of POV-Ray rather than the real deal. Although the software is licensed under the AGPL and therefore "free" as per the definition of the Free Software Foundation, trademark laws still apply, and "POV-Ray" is a trademark of Persistence of Vision Raytracer Pty. Ltd.

**Comment by trevorsandy** [comment]
Very well. Understood. 

With this, It will not be necessary to modify anything for the Unix platform. 

Cheers,
