### ISSUE TITLE
Start menu shortcut just says "POV-Ray".

### ISSUE THREAD

**Issue by posfan12** [POV-Ray/povray#262]
The shortcut created for the .exe in the start menu just says "POV-Ray". This makes it hard to tell the different versions - e.g. beta versions - apart. Please add the version number to the shortcut text. The more detailed and specific the better IMO.

**Comment by c-lipka** [comment]
Is this still an issue?

**Comment by posfan12** [comment]
Dunno. I can't uninstall the current beta to test the new beta. See my post in p.windows.

**Comment by posfan12** [comment]
I just uninstalled the beta and installed RC1. The same problem exists still. The Start Menu shortcut says "POV-Ray v3.7" instead lof "POV-Ray v3.7 RC1".

**Comment by posfan12** [comment]
I just uninstalled the 3.7.0 and the beta, and installed RC1. The same problem persists. The Start Menu shortcut just says "POV-Ray v3.7" instead of "POV-Ray v3.7.1 RC1".

**Comment by c-lipka** [comment]
Uh... the original complaint was that it just said "POV-Ray". According to your recent findings this is no longer the case.

The current intentional behaviour is that betas should identify as "POV-Ray v3.7-beta", while release candidates and releases proper should identify as "POV-Ray v3.7".

The primary reason we're not being even more specific is that v3.7.1 is designed to _supersede_ v3.7.0 anyway, rather than live alongside it. (Whether that is a good choice might be debatable, but we're doing this to honor a long-standing promise made in the docs; see http://wiki.povray.org/content/Documentation:Windows_Section_3#Publishing_via_Group_Policy.)

**Comment by posfan12** [comment]
That is strange. Most of the commercial software on my PC don't list the version number in the Start Menu, but a lot of the FOSS software do. For instance, Battle for Wesnoth 1.12.5, ImageMagick 6.9.2 Q16 (64-bit), Inkscape 0.91.

**Comment by posfan12** [comment]
Okay, things are now improved.

**Comment by c-lipka** [comment]
Judging by the discussion, it would seem to me that the issue has been fixed - to the extent that we intend to, ayway.
