### ISSUE TITLE
checking out gives error:The XML response contains invalid XML

### ISSUE THREAD

**Issue by RolfKluinhaar** [POV-Ray/povray#321]
..
D:\Temp\povray.git\branches\feature\specular_knockout\distribution\ini\tgaflc.ini
D:\Temp\povray.git\branches\feature\specular_knockout\distribution\ini\tgafli.ini
D:\Temp\povray.git\branches\feature\specular_knockout\distribution\ini\zipflc.ini
D:\Temp\povray.git\branches\feature\specular_knockout\distribution\ini\zipfli.ini
D:\Temp\povray.git\branches\feature\specular_knockout\distribution\platform-specific
D:\Temp\povray.git\branches\feature\specular_knockout\distribution\platform-specific\windows
D:\Temp\povray.git\branches\feature\specular_knockout\distribution\platform-specific\windows\Help
The XML response contains invalid XML
Completed!

**Comment by c-lipka** [comment]
`INSUFFICIENT DATA FOR MEANINGFUL ANSWER.`
-- Multivac

Please don't just paste program output into an issue report; we're not telepaths, and therefore can only make wild guesses as to what command you were using at that time.

Also, if this is output of some git command (as I currently presume), please note that we can't give you much in terms of support; in a nutshell, we just shove data into GitHub and hope for the best. If you have trouble retreiving that data from GitHub, the issue is either on your computer or on GitHub's servers.

**Comment by RolfKluinhaar** [comment]
Sorry Christoph, I forgot to post the leading info.

Under windows the graphical interface of 'Tortoise SVN' gave the error when checking out https://github.com/POV-Ray/povray.git.

Under Linux (raspbian-jessie distrib.) : 
svn checkout https://github.com/POV-Ray/povray.git

Both OS' gave this error.

Rolf.

**Comment by c-lipka** [comment]
Why would you try to use SVN to check out a Git repository?

**Comment by c-lipka** [comment]
Please be advised that the POV-Ray repository on GitHub is a Git repo. While GitHub _happens_ to allegedly provide access via SVN (see https://github.com/blog/626-announcing-svn-support), we as the POV-Ray dev team provide no support for that mechanism whatsoever. Instead, we recommend retrieving the source files either via a Git client or via ZIP file download.

If you do want to use SVN to retrieve the contents of the repo, please contact GitHub support to solve any issues you may encounter on that route. Whatever the problem is, it is most certainly beyond our control.
