### ISSUE TITLE
IO Restrictions Prohibit write access to 'imgpath' 3.7.0 win

### ISSUE THREAD

**Issue by jmichae3** [POV-Ray/povray#324]
### Environment

  - Source code Git tag: v3.7.0.0
  - POV-Ray version: v3.7.0+msvc10.win64
  - Operating system: Windows 7
  - Hardware platform: x86-64

### Steps to Reproduce

 1. don't know what causes it. full control over dir, can copy files in that target dir and have no write issues. I suspect bad pov-ray code is preventing writing the image. need working release that also does not whitewash the images like 3.7.0 does.

### Expected Behavior

expected image to be written to directory with full user account permissions on windows.

### Actual Behavior

Error when writing image:
IO Restrictions Prohibit write access to 'imgpath'

### Render Settings

~~~
; Persistence Of Vision raytracer version 3.5 sample file.

Width=2000
Height=900
Declare=monitors=2

Antialias=On

Antialias_Threshold=0.3
Antialias_Depth=3
;Test_Abort_Count=100
Input_File_Name=sign-abcd.pov
Output_File_Name=abcd
Output_File_Type=J
Output_Alpha=off
File_Gamma=sRGB
Display_Gamma=sRGB
;assumed_gamma=sRGB     ;causes error even though it's in manual
Bits_Per_Color=16

;Initial_Frame=1
;Final_Frame=150
;Initial_Clock=4.5
;Final_Clock=-11

;Cyclic_Animation=off
;Pause_when_Done=off


; Author: Jim Michaels
; Creation Date: 11/17/2006
; Current Date: 4/19/2008
; Version: 2.2
; Abstract: crossroads signpost with many signs pointing in many directions
; Copyright 2006, 2008 Jim Michaels
~~~

### Scene

any scene file

### Output

can't copy the render message output, it's not copyable. no content menu for that either.
the text is

~~~
IO Restrictions Prohibit write access to 'imgpath'
~~~

### Suggested Solution

stop reading when you are supposed to be writing.

**Comment by jmichae3** [comment]
this seems to be caused by not having an INI file. strange cause for a write error on a disk with FULL permissions on my user account.

**Comment by c-lipka** [comment]
Took the liberty to strip irrelevant stuff from your issue report,

**Comment by c-lipka** [comment]
> this seems to be caused by not having an INI file. 

Please specify more precisely what you mean by this:

(A) Rendering a `.pov` file without an associated `.ini` file: This shouldn't be a problem.

(B) Rendering without a "PVENGINE.INI": Yes, that would indeed be a problem, as this file specifies (among other stuff) the directories POV-Ray is allowed to write to.

> strange cause for a write error on a disk with FULL permissions on my user account.

The mechanism you're seeing is an additional safeguard that goes beyond the Windows access rights. POV-Ray's scene description language is powerful enough to wreak havoc on your computer, so POV-Ray bars itself from writing (or even reading from) any files anywhere except where explicitly allowed via that PVENGINE.INI, so that you don't have to worry about malign scene files when sharing with other people.

I very much presume a user error as the cause for your problems, and would like to invite you to our newsgroups on <http://news.povray.org> (or <news://news.povray.org> if you prefer access via a newsreader), where we will gladly provide additional support.

**Comment by jmichae3** [comment]
you mean once I start a new install of pov-ray 3.7.0, it deletes povray.ini and quickres.ini? ohhh, ninny, that's bad! :-)
sounds like a real bug there! -------------
 Jim Michaels<jmichae3@yahoo.com> http://www.JesusnJim.com (computer repair info, programming)

**Comment by jmichae3** [comment]
what I meant was, without  an extra .ini file that matches the .pov file.
 -------------
 Jim Michaels<jmichae3@yahoo.com> http://www.JesusnJim.com (computer repair info, programming)

**Comment by c-lipka** [comment]
Took the liberty to strip superfluous quoted text from your comments.

**Comment by jmichae3** [comment]
you are closed too. the function that is supposed to write is doing reads in 3.7.0.

**Comment by c-lipka** [comment]
> the function that is supposed to write is doing reads in 3.7.0.

I guess someone would have noticed by now if some code intended to write stuff were instead reading stuff. It tends to mess up data, you know.

Come and join us on our newsgroups to discuss this issue further, and if we find any substantiation to your claims that there's something wrong, I'll gladly re-open this issue.
