### ISSUE TITLE
feature request: conversion from string to datetime() float

### ISSUE THREAD

**Issue by jmichae3** [POV-Ray/povray#330]
### Summary

feature request: conversion from string to datetime() float
datetime is an output only function. 
related input functions are needed to convert a date or date and time string or date or date and time integers to the float which datetime() needs for input. 
currently manual only says you can use the value now. this is not helpful when you need a date in the past.

**Comment by c-lipka** [comment]
> currently manual only says you can use the value now. this is not helpful when you need a date in the past.

No, that's not what the manual says. The manual clearly document the value as "the time elapsed since 2000-01-01, 00:00:00 GMT in days".

**Comment by c-lipka** [comment]
Took the liberty to trim redundant / ballast information from your issue report. Please be so kind as do that yourself in the future, as requested in the template. Thank you for your cooperation.

**Comment by c-lipka** [comment]
Date/time conversion isn't a core functionality of a raytracer, and therefore a good case would have to be made where such conversion: (1) would actually be relevant, (2) could not be solved reasonably easy via existing mechanisms such as macros or user-defined functions, and (3) would be reasonably easy to design and implement as an integral part of POV-Ray.

The `now()` and `datetime()` team of functions was implemented specifically to allow insertion of the current date/time into a scene, to keep track of when the image was rendered. While the initial idea was for a monolithic function (essentially `datetime(now())`), it was decided that a separate `now()` function would have its own merits (e.g. to compute the position of celestial bodies depending on the current date and time) and would be not much added effort.

Adding a function to convert from a string back to a `now()`-compatible numeric value would probably open up a can of worms, as date and time formats are a pretty complicated matter, with different date formats, timezones and whatnot.

Functions to convert from numeric year, month and day values to a `now()`-compatible numeric value would be less messy to implement, but since the format is well-documented, such conversion can be implemented quite easily in the form of a macro or even user-defined function, by any user who finds themselves in frequent need of such functionality.

I'm therefore closing this feature request.
