### ISSUE TITLE
problems with 3.7.0 manual, syntax not spelled out in detail

### ISSUE THREAD

**Issue by jmichae3** [POV-Ray/povray#333]
### Summary

the include files are convenient, but the manual relies on them too heavily for glass section of the manual like ior. I cannot make my own glass without the include files because manual doesn't show how anymore. same with wood.
please include specs on IOR, caustics, and wood, image map, patterns, NORMAL_LIST, quilted details as in what I can fill it in with, etc. also, the manual is one huge web page. break it up into smaller ones so it can be indexed. indexing is broken.

many times, the spec for a keyword is not listed and even when it's listed, we don't know what we can fill in for all the items listed, some are not mentioned as to what they are, like NORMAL_LIST. 

please go through the manual to
- see where a syntax is needed (we can't guess)
- please spell out ALL the syntax as to what it can be filled in with (like an object?) color? texture? pigment? image_map? number? vector? maybe what the item means? if needed, link item to section in manual that describes it. the chm manual has a convenient back button.

**Comment by c-lipka** [comment]
You can always look at the include files to see how glass is actually modeled.

If you want to get actively involved in helping us improve our documentation, please visit the `povray.documentation.inbuilt` newsgroup at <news://news.povray.org> or <http://news.povray.org>, or the Wiki at <http://wiki.povray.org>.

**Comment by c-lipka** [comment]
Took the liberty to trim ballast from your issue report.

**Comment by c-lipka** [comment]
> indexing is broken

You didn't specify the POV-Ray version you are using, so I presume v3.7.0.
The index of that version's inbuilt help (`.chm` file) is indeed broken due to limitations of the help file viewer, but this is a known issue and has already been addressed for future versions.

Addressing the issue for v3.7.0 would be prohibitively difficult (it turned out to require extensive restructuring of the documentation on our Wiki, which is the place where we're actually maintaining the docs), but you could resort to using a help file from a newer version; just replace `povray37.chm` from your v3.7.0 installation with `distribution/platform-specific/windows/Help/povray.chm` from the `release/v3.8.0` branch (make sure to rename the file). Features new in v3.8.0 should be clearly marked as such in the help file.

As for your other complaints about the documentation contents, I'd like to point you to our newsgroups or the Wiki (see my earlier comment), as our documentation work is still focused there rather than on GitHub.
