### ISSUE TITLE
An installation directory has wrong path, on ./configure <...>

### ISSUE THREAD

**Issue by zebulon-1st** [POV-Ray/povray#374]
### Summary
On ./configure, the list of installation directories shows one of them has wrong path if neither using global installation nor using actual user HOME path local installation.

I have my own HOME that is "/home/joe". But, because I have already another version of povray installed locally in it, and I don't want to uninstall it before, I made another home directory to store the 3.7-stable locally in it.
So, I would use `PREFIX=/home/povray-3.7-stable` instead of `PREFIX=/home/joe` (which = "$HOME").

### Environment

  - Source code Git tag: branch=3.7-stable, VERSION file contains 3.7.0.8 (after prebuild.sh in unix/)
  - Operating system: Debian 9 Stretch stable (Linux debian-1 4.9.0-9-amd64 # 1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux)
  - Hardware platform: x86-64
  - Compiler: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

### Unix Build Command Sequence

~~~
cd unix ; prebuild.sh ; cd ..
./configure CC=gcc CXX=g++ COMPILED_BY="Frantz [zebulon] Balinski <hidden here@hidden here>" --prefix="/home/povray-3.7-stable" --enable-watch-cursor --disable-io-restrictions --with-x
~~~

### Unix Configure Output

~~~
...
The POV-Ray components will be installed in the following directories:
  Program (executable):       /home/povray-3.7-stable/bin
  System configuration files: /home/povray-3.7-stable/etc/povray/3.7
  User configuration files:   /home/joe/.povray/3.7
  Standard include files:     /home/povray-3.7-stable/share/povray-3.7/include
  Standard INI files:         /home/povray-3.7-stable/share/povray-3.7/ini
  Standard demo scene files:  /home/povray-3.7-stable/share/povray-3.7/scenes
  Documentation (text, HTML): /home/povray-3.7-stable/share/doc/povray-3.7
  Unix man page:              /home/povray-3.7-stable/share/man
===============================================================================
~~~

### Steps to Reproduce

```
# I already have a version of povray (3.7RC7 + mandelbulb patch) installed in my /home/joe session -- and I use it at the moment
# Now, create a special local installation home directory for v3.7 stable
cd /home
sudo mkdir povray-3.7-stable
sudo chown -R "$USER:$USER" povray-3.7-stable

# Configure 3.7 stable for unix
cd ~/Sources
mkdir povray-3.7-stable
cd povray-3.7-stable
git clone --branch 3.7-stable https://github.com/POV-Ray/povray.git
cd povray
cd unix; ./prebuild.sh; cd ..
```

### Expected Behavior

The `User configuration files` should be `/home/povray-3.7-stable/.povray/3.7` ($PREFIX/.povray/3.7)

### Actual Behavior

The `User configuration files` directory is set to `/home/joe/.povray/3.7` ($HOME/.povray/3.7)

**Comment by zebulon-1st** [comment]
Note : version 3.8 alpha has the same error.

**Comment by c-lipka** [comment]
This is actually the intended behaviour. The `PREFIX=` setting is there to change the location of the files _shared by all users_, so that you can choose e.g. whether to install somewhere in `/bin/`, `/etc/bin` or whatever.

The location of user-specific files is currently hard-coded (except for the `$HOME` directory portion). For the sake of convenience the `./configure` script displays the corresponding directory for the installing user, but it gives no control over it. You'd need to modify the source files to change it.

It may be sufficient to change the `AC_INIT(..., [povray])` invocation in `unix/configure.ac` (somewhere around line 45; you'll need to re-run `unix/prebuild.sh`), but I can't guarantee, as I'm not really a Unix jockey.

(Also, I'd highly recommend changing the path for the patched version, rather than the official one.)

**Comment by zebulon-1st** [comment]
Another way, is to add a user (create a new user session) that will get this version installed in. But I'ill to set user (su) to this one, when I would use this version instead of the one I already have.
By this way, I even could install the v3.8, in another user session, too.

So I could have :
- the mandelbulb patched 3.7RC7 I still have installed in my $HOME
- the stable release 3.7 (in /home/user37/, for example), "joe" using it with a "su user37".
- the alpha release 3.8 (in /home/user38/ for example), "joe" using it with a "su user38".

And then, I haven't to break the initial code to adapt it for this particular need.

**Comment by wfpokorny** [comment]
I routinely have and run multiple versions of POV-Ray on my Ubuntu system. As Christoph said user files are hard coded in $HOME/.povray... When POV_Ray runs it always uses those user files. I specifically don't want this behavior when testing versions of POV-Ray. 

So, I use the unix POVINI environment variable point to the common povray.ini file I want to use with my day to day work. The location for me today is $HOME/pov/povray.ini but i can be whatever.  

I create then for each other installed version of POV-Ray bash wrapper scripts (p370, p380,pJG,pUber, etc) which internally look roughly like this: 

 #!/bin/bash
export POVINI=/run/shm/tmpDir/tmpUser/MyP380/etc/povray/3.8/povray.ini
echo "" >$HOME/.povray/3.8/povray.ini
echo "" >$HOME/.povray/3.8/povray.conf
/run/shm/tmpDir/tmpUser/MyP380/bin/povray $@
exit $?

The echoes make sure the usual $HOME/.povray  files are there, but empty. Instead of the command povray I use p370 or whatever to switch versions. 

Perhaps something like this could work for you too? I see as I've typed this you are thinking multiple users. That should work too without modification of the build process or anything else. Ringing in my head says there is an extra flag to really change the effective $HOME or not with su...    

Probably the build / run-time process could be more flexible with respect to multiple versions of POV-Ray - but I've never really thought about the particulars of such a change.

**Comment by zebulon-1st** [comment]
@wfpokorny 
Well... my own idea about using extra users is not the best way, because I'm logged in as user "joe", even if I "su pov37" or "su pov38" in a shell :
1) I can't use +d povray option. X server cannot find display for these extra users : "no protocol", "can't open/find display :0.0", ... And povray just crash with a beautifull 
2) because of the rights that each user have on his own files, it's harder to use files from another user. Or I have to create a special group "povray", and add each user in it ; even "joe".
...
So, I think your method is simplest and easier to set.

**Comment by zebulon-1st** [comment]
Was not a really issue, since "This is actually the intended behaviour".
