### ISSUE TITLE
Building on postmarketOS on PinePhone

### ISSUE THREAD

**Issue by chiraag-nataraj** [POV-Ray/povray#400]
The build system needs tweaking in order to work on postmarketOS (and likely other systems with busybox instead of coreutils). 

* In the `configure` script, the `stat` calls need to use `-c` instead of `--format`.
* Had to deal with the same issue as #10 (same files).

These were the only changes needed.

**Comment by c-lipka** [comment]
Issue #10 should have been fixed ages ago; what version of POV-Ray are you trying to build?

**Comment by c-lipka** [comment]
Looks like you are trying to compile v3.7, which was not developed with busybox-based target environments in mind. Fixing the `configure` script should be fairly easy, but addressing the data types issue might be fraught with danger of breaking other things, so we're unlikely to do that.

If you feel comfortable applying the workaround described in #10 manually, we recommend you do that. Otherwise you might want to try one of the latest tagged v3.8 development versions instead, which should have both issues fixed.

**Comment by c-lipka** [comment]
Please try whether the `hotfix/v370_issue400` branch addresses your issues (and doesn't introduce any new ones). All going well, _both_ issues you've mentioned should be gone.

**Comment by c-lipka** [comment]
Should be all fixed in `3.7-stable` branch (v3.7.0.9).
Corresponding fix in v3.8 still pending, but will follow same pattern (`stat` issue only; the other issue has already been fixed there).

**Comment by chiraag-nataraj** [comment]
Thanks @c-lipka! In the meantime, I've installed Mobian on my PinePhone, but if I reinstall postmarketOS again, I'll try compiling POV-Ray again.
