### ISSUE TITLE
README: dependency on libboost-thread-dev is missing

### ISSUE THREAD

**Issue by fjf2002** [POV-Ray/povray#401]
In document https://github.com/POV-Ray/povray/blob/master/unix/README.md,

dependency on libboost-thread-dev is missing.

Regards,
fjf2002

**Comment by c-lipka** [comment]
This is entirely intentional. As of v3.8.0-alpha.10064268, POV-Ray should no longer require `libbost-thread-dev`, as it has been updated to rely entirely on C++11 features instead of boost for multithreading.

Should you experience any build errors without first installing `libboost-thread-dev`, please let us know.
