### ISSUE TITLE
References to bugs.povray.org

### ISSUE THREAD

**Issue by 0joshuaolson1** [POV-Ray/povray#55]
Is http://news.povray.org/povray.bugreports/ the replacement?

I realize the irony of making this in the new GitHub issue section.

**Comment by wfpokorny** [comment]
I'm just another user and join you in wondering about bug reporting. 

The old 3.7 flyspray bugs.povray.org  site has been unreachable to me for a while & I wonder what might happen to the open bugs documented there if the site is really gone.   

clipka has posted in the past that he'd like new definite bugs reported here as it helps with tracking bugs and fixes. 

So, I'd guess the current process would be to get confirmation for a bug via the bugreports newsgroup if possible as that is still where most follow along, after which we'd open an issue here.

Bill P.

**Comment by c-lipka** [comment]
As a matter of fact, the `povray.bugreports` newsgroup on `news.povray.org` is the _oldest_ bug reporting channel still in service. The Flyspray installation on http://bugs.povray.org was introduced during the beta phase of POV-Ray 3.7.0, but is admittedly suffering some neglect since we've moved the source code repository to GitHub, as GitHub issues is now a more natural choice.

**Comment by MrMormon** [comment]
@c-lipka I think this should stay open until a PR corrects what's in the title.

**Comment by c-lipka** [comment]
Ah, misunderstanding -- I thought this was just an inquiry.

**Comment by c-lipka** [comment]
I _think_ we should have gotten the last of them just now. If you find any more, let us know.
