### ISSUE TITLE
Can't visit www.povray.org

### ISSUE THREAD

**Issue by yaolubrain** [POV-Ray/povray#58]
Hi,

I can't visit www.povray.org for weeks. Is there anything wrong with the organization?

**Comment by c-lipka** [comment]
No problem here, so whatever the problem is, it's probably located somewhere between your computer and your internet provider.

**Comment by chris20** [comment]
There is a known issue with users downstream from Telia. They are not honoring the route for our class C. This is affecting people in various parts of Scandinavia and Europe at least. Below is the message we have on povray.org regarding the issue:

-----------------------------

We've become aware that since late November some visitors in the Scandinavian region have been unable to access povray.org and its related sites via their broadband connection, but find that when using a mobile connection the site works fine.

This issue affects visitors whose ISP's rely on TeliaSonera for transit or routing information (while there may be other backbone providers affected, we have not received examples other than Telia). Basically Telia are not receiving (or not accepting, we are not sure which) routing information for the network that povray.org is hosted on (203.29.75.0/24, advertised on AS6062).

At this point the matter is out of our hands as it involves backbone providers and how they exchange BGP routing information. The issue has been brought to the attention of providers in both the USA (where our network is hosted) and Sweden, and we can only wait to see if or when they will resolve it.

Please also note that affected visitors will probably not be able to successfully email us regarding the issue if they use their ISP-provided email accounts as these will generally use the same routing tables as used for general web browsing. Using GMail or other non-ISP-specific services ought to work.

We will update this post as more information becomes available.

**Comment by c-lipka** [comment]
Is this still an issue?

**Comment by c-lipka** [comment]
Closed due to lack of further information.
